// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx_P8hwMIG70nKApL-XtkG4JwbrOqs9Q0',
    appId: '1:18186875447:web:b861cf953cf8a1674305b2',
    messagingSenderId: '18186875447',
    projectId: 'evently2-75ea0',
    authDomain: 'evently2-75ea0.firebaseapp.com',
    storageBucket: 'evently2-75ea0.firebasestorage.app',
    measurementId: 'G-2SJYG67NTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJw3IwY_I2MdN05GEmQbtPOYGsaNwsbns',
    appId: '1:18186875447:android:0f88b6a880b30eb24305b2',
    messagingSenderId: '18186875447',
    projectId: 'evently2-75ea0',
    storageBucket: 'evently2-75ea0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwvb_dVulmcracKPvogLghLF94K-pPH_s',
    appId: '1:18186875447:ios:a702360206fadba04305b2',
    messagingSenderId: '18186875447',
    projectId: 'evently2-75ea0',
    storageBucket: 'evently2-75ea0.firebasestorage.app',
    iosBundleId: 'com.example.enntly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwvb_dVulmcracKPvogLghLF94K-pPH_s',
    appId: '1:18186875447:ios:a702360206fadba04305b2',
    messagingSenderId: '18186875447',
    projectId: 'evently2-75ea0',
    storageBucket: 'evently2-75ea0.firebasestorage.app',
    iosBundleId: 'com.example.enntly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx_P8hwMIG70nKApL-XtkG4JwbrOqs9Q0',
    appId: '1:18186875447:web:233c38b7ef818d8e4305b2',
    messagingSenderId: '18186875447',
    projectId: 'evently2-75ea0',
    authDomain: 'evently2-75ea0.firebaseapp.com',
    storageBucket: 'evently2-75ea0.firebasestorage.app',
    measurementId: 'G-W2CKLLH0E8',
  );
}
